// <auto-generated />
using System;
using EnglishExam.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnglishExam.DataAccess.Migrations
{
    [DbContext(typeof(EnglishExamDbContext))]
    [Migration("20220104210603_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EnglishExam.Model.Concrete.Constants", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsDelete")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsDeleted")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Constants");
                });

            modelBuilder.Entity("EnglishExam.Model.Concrete.ConstantsValues", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConstantsId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsDelete")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Order")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConstantsId");

                    b.ToTable("ConstantsValues");
                });

            modelBuilder.Entity("EnglishExam.Model.Concrete.Exam", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamText")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("EnglishExam.Model.Concrete.ExamList", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionA")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionC")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionD")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamLists");
                });

            modelBuilder.Entity("EnglishExam.Model.Concrete.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnglishExam.Model.Concrete.ConstantsValues", b =>
                {
                    b.HasOne("EnglishExam.Model.Concrete.Constants", "Constants")
                        .WithMany("ConstantsValues")
                        .HasForeignKey("ConstantsId");

                    b.Navigation("Constants");
                });

            modelBuilder.Entity("EnglishExam.Model.Concrete.ExamList", b =>
                {
                    b.HasOne("EnglishExam.Model.Concrete.Exam", "Exam")
                        .WithMany("ExamLists")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("EnglishExam.Model.Concrete.Constants", b =>
                {
                    b.Navigation("ConstantsValues");
                });

            modelBuilder.Entity("EnglishExam.Model.Concrete.Exam", b =>
                {
                    b.Navigation("ExamLists");
                });
#pragma warning restore 612, 618
        }
    }
}
